### ISSUE TITLE
github.com/distroy/ldgo@v0.0.28 Checksum Mismatch

### ISSUE THREAD

**Issue by psky1111** [distroy/ldgo#8]
Hi! Could you plz help us solve a problem. We used ldgo:0.0.28 in the yesterday morning, but it can not pass the checksum today. We try  go clean -cache and rm go sum and it still can not pass the checksum. Is there any problem that we use the last version to replace 0.0.28? Or, is there any method we can do to pass the checksum?  Looking forward to your reply！

**Comment by distroy** [comment]
@psky1111 please upgrade the version

**Comment by distroy** [comment]
please update the version
